# configuring travis CI for the docker-react github repo
# ! when we are using we root-access permissions
language : generic
sudo : required
services:
  - docker

# * some series of commands that execute before running tests or deploying code 
before-install:
  - docker build -t jaladisishir/docker-react .

# * some series of commands that execute when tests need to be executed 
# -e to return the result after running the test ,which is not the default behavior of npm test-providing an interface
script:
  - docker run -e CI=true jaladisishir/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-355294214850"
  bucket_path: "docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
